import { Berkshire_Swash, Inter } from "next/font/google";
import "./globals.css";

const berkshireSwash = Berkshire_Swash({
  weight: '400', // The only available weight for Berkshire Swash
  subsets: ['latin'], // Choose the appropriate subset
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={berkshireSwash.className}>{children}</body>
    </html>
  );
}
